name: Node CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      run: |
        npm install
        npm test
        npm run build
      env:
        CI: true
    - name: docker image 1
      env:
        BRANCH: ${{ github.ref }}
      run: |
        docker build -t docker.io/xebxke/xke-github-actions:${BRANCH#/refs/heads/}-${github.sha} .
      
